  <ul id="ul_nav" >
    <li class="li_nav"><a href="index.php">Index</a></li>
    <li class="li_nav"><a href="product.php">Products</a></li>
    <li class="li_nav"><a href="enquire.php">Enquiries</a></li>
    <li class="li_nav"><a href="about.php">About</a></li>
    <li class="li_nav"><a href="enhancements.php">Enhancements</a></li>
    <li class="li_nav"><a href="manage.php">Manage</a></li>
  </ul>
